### PR TITLE
Indent providers JSON file

### PR DESCRIPTION
**Pull request by deeplook**
This makes the list of providers easier and nicer to read and diff on GitHub while adding only a little more white space which is considered cheap nowadays.

### CODE REVIEW

**Comment by martinfleis** [comment]
Hi @deeplook,

Thanks for the suggestion. The `providers.json` is autogenerated via `make compress` which calls `provider_sources/_compress_providers.py`. So if we want to indent it (as we do with input JSONs stored in `provider_sources`) we should add `indent=4` in here: https://github.com/geopandas/xyzservices/blob/ee5ade0745103a73ae5f587b47c505348288d246/provider_sources/_compress_providers.py#L27-L28

Otherwise, this change will not persist and the next scheduled GHA update will again result in the compressed version.

I just tried and there's essentially no difference in the file size. If you want to adapt the PR to make the actual code change (and run`make compress`), feel free to do so!

**Comment by jorisvandenbossche** [comment]
I think the idea was to have the actual sources to be pretty-printed, i.e. `leaflet-providers-parsed.json` and `xyzservices-providers.json` in the "provider_sources" subdir (so you can indeed easily read this and check the diff), but have the combined file that is distributed to be minimized?

**Comment by jorisvandenbossche** [comment]
But reading Martin's response now, if there is no difference in file size (and it's also not big anyway), then yes, we can have all sources pretty-printed

**Comment by martinfleis** [comment]
@jorisvandenbossche that was the idea but the JSON is 75 KB vs 107 KB so I guess we can pretty-print this one as well. It may improve user experience.

**Comment by deeplook** [comment]
@martinfleis 

> Thanks for the suggestion. The providers.json is autogenerated via make compress which calls provider_sources/_compress_providers.py. So if we want to indent it (as we do with input JSONs stored in provider_sources) we should add indent=4 in here: 

Thanks for the pointer! Done now...

**Review by martinfleis — APPROVED** [review]
Thanks! (I just pushed tiny docs change to accommodate this PR)

**Pull request merged**
